{{ config(materialized='table') }}
select
   ORDERID,
	SHIPPOSTALCODE,
	ORDERDATE,
	SHIPADDRESS,
	SHIPCOUNTRY,
	EMPLOYEEID,
	FREIGHT,
	SHIPNAME,
	SHIPCITY,
	CUSTOMERID,
	REQUIREDDATE ,
	SHIPREGION,
	SHIPVIA,
	SHIPPEDDATE
from NORTHWIND_RAW.STAGING_FIVETRAN_DBO.ORDERS